apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: ghcr.io/zhangtao1994hk/argocd-apps/backend
  newName: ghcr.io/zhangtao1994hk/argocd-apps/backend
  newTag: 84941bc4589ec65d59865c00e53250e2997d565e
- name: ghcr.io/zhangtao1994hk/argocd-apps/dao
  newName: ghcr.io/zhangtao1994hk/argocd-apps/dao
  newTag: 4ea580f5bbf171f314ffd86379126a02d85d7c1e
- name: ghcr.io/zhangtao1994hk/argocd-apps/frontend
  newName: ghcr.io/zhangtao1994hk/argocd-apps/frontend
  newTag: cfdec143a8d678c9b24e8269553ae9a8799e2c39
