apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.14.1
    # 这一行是关键：只渲染 crds 目录下的东西，不渲染 templates
    helm:
      #includeCRDs: true
      values: |
        crds:
          enabled: true
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        prometheus:
          enabled: false
        prometheusOperator:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true # 开启 SSA 解决 Annotation 超限问题
