apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: middleware
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.15.0 # 建议锁定版本
    chart: mysql
    helm:
      values: |
        
        # 镜像显式指定，避免默认 tag 变化导致 ImagePull / Image not found
        global:
          imageRegistry: docker.io

        image:
          repository: bitnami/mysql
          tag: "8.0.35-debian-11-r0"
        
        metrics:
          image:
            repository: bitnami/mysqld-exporter
            tag: "0.15.0-debian-11-r70"
        
        # 2. 设置强密码 (生产环境建议用 Secret 引用)
        auth:
          rootPassword: "777777"
          database: "appdb"
          username: "root"
          password: "777777"
        
        # 3. 开启数据持久化 (非常重要，否则重启数据就没了)
        primary:
          persistence:
            enabled: true
            size: 10Gi
            
        # 4. 🌟 开启 MySQL Exporter (内置支持)
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true # 如果你有 Prometheus Operator，开启这个会自动发现
            namespace: monitoring # 指向你的 Prometheus 所在的命名空间
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

