apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.147.1 
    helm:
      values: |
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-contrib
        # 核心配置：定义数据流向
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          
          processors:
            batch:
              timeout: 10s
              send_batch_size: 1024
              send_batch_max_size: 2048

          exporters:
            # 1. 转发 Trace 到 Tempo
            otlp/tempo:
              endpoint: "tempo-app.monitoring.svc.cluster.local:4317"
              tls:
                insecure: true
            
            # 2. 转发 Metrics 到 Prometheus
            prometheusremotewrite:
              endpoint: "http://kube-prometheus-stack-prometheus:9090/api/v1/write"
              timeout: 30s
              max_batch_request_parallelism: 10 
              remote_write_queue:
                enabled: true
                num_consumers: 10      # 默认是5，加倍消费速度
                queue_size: 5000 
              retry_on_failure:
                enabled: true
                initial_interval: 5s
                max_interval: 30s
                max_elapsed_time: 120s



          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp/tempo]
              metrics:
                receivers: [otlp,prometheus]
                processors: [batch]
                exporters: [prometheusremotewrite]
              logs:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [debug]

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
