apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.17.1
    helm:
      values: |
        config:
          clients:
            - url: http://loki-app-gateway:80/loki/api/v1/push
          snippets:
            pipelineStages:
              - docker: {}
        serviceAccount:
          create: true
        tolerations:
          - effect: NoSchedule
            operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
