apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.14.1
    helm:
      # 显式禁用 CRD 的安装，因为第一个应用已经处理过了
      values: |
        crds:
          enabled: false
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
        grafana:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: traefik  # K3s 默认 Ingress Controller
            hosts:
              - grafana.local          # 这里设置你自定义的域名
            paths:
              - /
        alertmanager:
          enabled: true
        prometheus:
          enabled: true
          prometheusSpec:
            remoteWriteDashboards: false 
            ingress:
              enabled: true
              ingressClassName: traefik # K3s 默认是 traefik
              hosts:
                - prometheus.local # 修改为你想要的域名
              paths:
                - /
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
