apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/zhangtao1994hk/argocd-apps.git' 
    path: .
    helm:
      valueFiles:
        - prometheus-values.yaml
      releaseName: kube-prometheus-stack
      chart: kube-prometheus-stack
      helmRepoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 82.14.1
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # 关键：使用 SSA 避免 Annotation 超限
  
