apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.14.1
    helm:
      # 显式禁用 CRD 的安装，因为第一个应用已经处理过了
      values: |
        crds:
          enabled: false
        prometheus-node-exporter:
          enabled: false
        kube-state-metrics:
          enabled: false
        grafana:
          enabled: false
        alertmanager:
          enabled: false
        prometheus:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
