grafana:
  enabled: true
  adminPassword: "admin"
  ingress:
    enabled: false # 先关掉 Ingress，测试通了再开
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100 
      access: proxy

prometheus:
  prometheusSpec:
    retention: 5d # 数据保留 5 天
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi # 开启持久化存储，防止重启丢失数据
