apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: backend-image
  newName: ghcr.io/zhangtao1994hk/argocd-apps/backend
  newTag: 440d7b7eb6d0e5a36cd774a36ebefc1b8c7209c2
- name: dao-image
  newName: ghcr.io/zhangtao1994hk/argocd-apps/dao
  newTag: 2f7e62a17c9aebf90b9289064e21d489f27aad83
- name: frontend-image
  newName: ghcr.io/zhangtao1994hk/argocd-apps/frontend
  newTag: 43b8791344e55248ba0ecf453f8ffd2de0f3d5ae
