apiVersion: v1
kind: Service
metadata:
  name: redis-svc  # 必须与下面的 Endpoints 名称一致
  namespace: middleware
spec:
  ports:
    - protocol: TCP
      port: 6379      # 集群内应用访问的端口
      targetPort: 6379 # 外部 Redis 的实际端口
# 注意：这里千万不要写 selector

---
# 2. 创建同名的 Endpoints，指向外部 IP
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-svc  # 必须与上面的 Service 名称完全一致！
  namespace: middleware
subsets:
  - addresses:
      - ip: 10.128.0.2   # 外部 Redis 的真实 IP 地址
    ports:
      - port: 6379         # 外部 Redis 的真实端口
