apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: middleware # 建议部署在专门的 middleware 命名空间
data:
  custom.cnf: |
    [mysqld]
    max_connections = 1000
    innodb_buffer_pool_size = 1G
    slow_query_log = 1
    long_query_time = 2
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
