apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: middleware
type: Opaque
stringData:
  # 数据库 root 密码
  MYSQL_ROOT_PASSWORD: "777777"
  # 注入给 Exporter 专用的连接配置文件
  .my.cnf: |
    [client]
    user=root
    password=777777
    host=127.0.0.1
    port=3306
