apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa # 建议和你的 deployment 名字关联
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1  
    kind: Rollout
    name: frontend # 这里必须精准匹配你 Deployment 的名字
  minReplicas: 2   # 最小副本数（最少跑几个）
  maxReplicas: 5  # 最大副本数（流量再大也不要超过这个数，防止爆仓）
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # 当 CPU 平均使用率超过 60% 时，开始扩容
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa # 建议和你的 deployment 名字关联
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1  
    kind: Rollout
    name: backend # 这里必须精准匹配你 Deployment 的名字
  minReplicas: 2   # 最小副本数（最少跑几个）
  maxReplicas: 10  # 最大副本数（流量再大也不要超过这个数，防止爆仓）
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # 当 CPU 平均使用率超过 60% 时，开始扩容
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dao-hpa # 建议和你的 deployment 名字关联
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1  
    kind: Rollout
    name: dao # 这里必须精准匹配你 Deployment 的名字
  minReplicas: 2   # 最小副本数（最少跑几个）
  maxReplicas: 10  # 最大副本数（流量再大也不要超过这个数，防止爆仓）
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # 当 CPU 平均使用率超过 60% 时，开始扩容
