apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-rollout.yaml
  - backend-analysis-template.yaml    
  - dao-rollout.yaml
  - dao-analysis-template.yaml 
  - frontend-rollout.yaml
  - frontend-service.yaml
  - frontend-analysis-template.yaml
  - hpa.yaml

