name: Build and Push Frontend Image

on:
  push:
    paths:
      - 'frontend/**' # 【修改点1】只监听 frontend 目录
  workflow_dispatch:

concurrency:
  group: git-push-to-manifests
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend # 【修改点2】镜像名改为 frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 确保写权限
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # 【修改点3】构建目录改为 frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update frontend image tag via kustomize
        run: |
          # 【修改点4】替换 frontend-rollout.yaml 中的镜像
          cd overlays/prod    
          kustomize edit set image ghcr.io/zhangtao1994hk/argocd-apps/frontend=ghcr.io/zhangtao1994hk/argocd-apps/frontend:${{ github.sha }}
          yq e '(.spec.template.spec.containers[] | select(.name == "frontend") | .env[] | select(.name == "APP_VERSION") | .value) = "${{ github.sha }}"' -i ../../base/frontend-rollout.yaml
 
      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add overlays/prod/kustomization.yaml  base/frontend-rollout.yaml
          

          git commit -m "chore(frontend): update image to ${{ github.sha }} [skip ci]" || echo "No changes to commit"
          
          # 【重点防御】先 pull 一下最新的代码再 push，防止多个 Action 同时修改代码导致冲突
          git pull --rebase origin main
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
